### ISSUE TITLE
interactive map not interactive via tablet

### ISSUE THREAD

**Issue by ccheitman** [CDRH/sparc#333]
Just tried to click on a room on the interactive map using my iPad (Safari browser) and I can't get any of the zones to load.

**Comment by karindalziel** [comment]
Further research: it does seem like we can accomplish this by using javascript to detect mobile and then only applying the scaling framework if the site is NOT mobile. 

On small touchscreens, the following demo is working for me OK:

http://nirak.net/uploads/sparcmap/

to zoom, I just use regular pinch and zoom gesture, and the links work

I had a lot of trouble getting the SVG to scale. I ended up putting `viewbox="4 2 90 90" ` on the `svg` element and `transform="scale(.165)"` on the `g` element surrounding the rest of the elements. I don't know why this worked, and cross device testing is necessary.

**Comment by karindalziel** [comment]
DOH found there is an option for this that prevents clicks by default. I missed the option when I looked at the library the first time. 

So, this is done, but I think the above solution might be a bit better in the long term if we want to implement it.
