### ISSUE TITLE
Link to unit n/a not working

### ISSUE THREAD

**Issue by karindalziel** [CDRH/sparc#344]
I assume because of the / in the URL?

https://salmonpueblo.org/explore/units?page=12
(see n/a unit)

**Comment by jduss4** [comment]
This works for me locally, though agreed that it doesn't work on production.
Also interestingly, I don't think it is getting to the rails app?  It is not showing the app's 404 error page.

**Comment by jduss4** [comment]
Using this solution gives 500 missing unit error instead of external to rails 400 error:  https://stackoverflow.com/a/9933890/4154134

`AllowEncodedSlashes NoDecode`

**Comment by techgique** [comment]
Using the `NoDecode` option is safe :+1:

**Comment by jduss4** [comment]
Addressed by this commit:  https://github.com/CDRH/sparc/commit/d924130d9ab2321edceed8ec0997a93bbd80c4e7
