### ISSUE TITLE
Idea: Hide any options that only have one option

### ISSUE THREAD

**Issue by karindalziel** [CDRH/sparc#365]
For instance, in the features table, `Real Features` is always blank, so there's nothing to choose. 

![screen shot 2018-05-11 at 12 49 49 pm](https://user-images.githubusercontent.com/284315/39938848-ddfd5760-5519-11e8-9408-43f9193e8b7f.png)

we could simply not show these options at all, or somehow tell the user that the option is not being displayed because there's only one option

I'm guessing right now this is only an issue if ALL the fields are blank for a column

**Comment by jduss4** [comment]
I would suggest this means that there is an error somewhere, either in the database ingest, the spelling for the field, the association, etc.  Somewhere something is wrong and we can either remove the field or we need to look into fixing it?

**Comment by karindalziel** [comment]
This appears to be fixed
