### ISSUE TITLE
Common Search by Strat Groupings

### ISSUE THREAD

**Issue by techgique** [CDRH/sparc#366]
We disabled this field because we were only getting matches for the "Other" value.

Doing a little investigating, it seems the Strat Groupings are not being set correctly when seeding Strat Type. `6` is the id for "Other" in the StratGrouping table.
```ruby
StratType.all.pluck(:code, :name, :strat_grouping_id)
   (0.3ms)  SELECT "strat_types"."code", "strat_types"."name", "strat_types"."strat_grouping_id" FROM "strat_types"
 => [["A", "Present Ground", 6], ["AB", "Present Ground and Post-Occupational Fill", 6], ["B", "Post-Occupational Fill", 6], ["C", "Structured Trash", 6], ["CT", "Structured Trash and Construction Debris", 6], ["CU", "Structured Trash and Disturbed Deposits", 6], ["D", "Artificial Fill", 6], ["E", "Roof Contact", 6], ["F", "Roof Itself", 6], ["FC", "Roof Itself and Structured Trash", 6], ["G", "Occupational Fill", 6], ["H", "Floor Contact", 6], ["I", "Floor Itself", 6], ["J", "Preoccupational Fill", 6], ["K", "Wall Foundation", 6], ["L", "Feature Fill", 6], ["M", "Secondary, Unstructured Trash", 6], ["N", "Natural-Slow Roof Fall", 6], ["O", "Zonal, Naturally Decayed Floors", 6], ["P", "Archaeological Backfill", 6], ["Q", "Zonal, Extramural Living Surface", 6], ["R", "Extramural Activity Surface", 6], ["S", "Contact Surface Between 2 Other Surfaces", 6], ["T", "Construction Debris", 6], ["TD", "Construction Debris and Artificial Fill", 6], ["U", "Disturbed Deposits", 6], ["V", "Natural Deposit with Some Artifacts", 6], ["W", "Material Found Within Walls", 6], ["X", "Unknown Deposit", 6]]
```

Relevant seeding code: https://github.com/CDRH/sparc/blob/master/db/seeds.rb#L972

I _think_ once this is fixed, we'll be able to use the code on my strata-search branch: https://github.com/CDRH/sparc/tree/strata-search
(Edit: I deleted the branch referenced here and used the code in #371 )

There are comments in the code there about:
- The Unit table not being able to associate with Strat Grouping because we were explicitly skipping the Unit table's association to `:strata`. We _may_ be able to remove this exception now that #358 has been merged. Or if work on #364 resolves intermingled query construction issues.
- CeramicClap searches resulting in more results than records in the table. This may also have been resolves by #358

**Comment by jduss4** [comment]
Associations addressed by https://github.com/CDRH/sparc/pull/368

**Comment by techgique** [comment]
Strata group searching restored in #371 , but separate bug relating to Unit and CeramicClap table results remains

**Comment by techgique** [comment]
Remaining issues noted in #372
